# Generated by Django 5.2.7 on 2025-10-23 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=100)),
                ('score_added', models.IntegerField()),
                ('log_entry', models.TextField()),
                ('threat_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='analyzer.threatsource')),
            ],
        ),
    ]
