# Generated by Django 5.2.7 on 2025-10-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_anomaly'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(max_length=2048)),
                ('status_code', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='anomaly',
            name='attacked_url',
            field=models.CharField(default='N/A', max_length=2048),
        ),
        migrations.AddField(
            model_name='threatsource',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
