# Generated by Django 5.2.7 on 2025-10-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_logentry_anomaly_attacked_url_threatsource_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='attacked_url',
            field=models.CharField(max_length=2048),
        ),
    ]
