# Generated by Django 5.2.7 on 2025-10-24 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_anomaly_details_logentry_user_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='threat_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='analyzer.threatsource'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='time_delta_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
